### ISSUE TITLE
Please provide a function to spawn a thread per CPU

### ISSUE THREAD

**Issue by joshtriplett** [stjepang/smol#101]
I'd love to have a helper function `smol::start_threads` that starts one thread per CPU, and either returns nothing, or returns a token that can be handed to a `smol::stop_threads` function to tell those threads to stop and then wait for them.

Alternatively, if it's simpler, I'd be happy with a function that takes a future and starts a thread pool before calling `block_on` on it, stopping the thread pool when the future finishes.

As discussed at https://www.reddit.com/r/rust/comments/g917ad/smol_stjepang_a_small_and_fast_async_runtime_for/fortim2/

**Comment by leo-lb** [comment]
Please see this crate: https://github.com/wusyong/smol-potat

There's right now no requirement for such ergonomic sugar to sit inside the smol crate itself

**Comment by joshtriplett** [comment]
For future reference: `smol::run` now does this by default.

Thanks, @stjepang!
