### ISSUE TITLE
Code of conduct contains "[INSERT CONTACT METHOD]"

### ISSUE THREAD

**Issue by ComputerDruid** [stjepang/smol#114]
First of all, thanks for having a code of conduct at all!

https://github.com/stjepang/smol/blob/6278e9f70b77c1d52cd3256ce30f5b3bf28956cc/CODE_OF_CONDUCT.md#enforcement

Still contains the placeholder value "[INSERT CONTACT METHOD]" when explaining how to contact the "community leaders responsible for enforcement".

To be clear, I don't need to use that right now, as I'm only just reading smol for the first time and haven't even had any community interaction yet. But it seems like something worth fixing before somebody does want to bring up an issue.

**Comment by stjepang** [comment]
Hey, thank you for noticing! I was sure that I filled in this placeholder but I guess that change somehow slipped through... Anyways, should be fixed now. :)

**Comment by ComputerDruid** [comment]
Fixed by 40d7998d9fb2317b04816282f5ec52c2e71bbd2f
