### ISSUE TITLE
Reliable deadlock on windows in Smol 0.1.5

### ISSUE THREAD

**Issue by nmccarty** [stjepang/smol#115]
Code to reproduce: 

https://gist.github.com/nmccarty/0df7130b40a62c380e8d0a3c46f48e86

Smol 0.1.5 seems to have introduced a regression on windows that causes the linked code snippet to run forever without terminating. The same code runs and terminates fine on linux and macos under smol 0.1.5, and under all three operating systems on smol 0.1.4. 

In particular, it appears line 88 is triggering the bug, if that line is removed, the code terminates normally on smol 0.1.5.

I apologize for reproduction not being as minimal as it could be, this bug manifested as one of my unit tests not terminating on windows, and this was produced by trimming portions out of that module until there was nothing else obvious to remove.

**Comment by nmccarty** [comment]
Using git-bisect using my example as a test reveals that commit [2ff45ece44](https://github.com/stjepang/smol/commit/2ff45ece44c4db50f6127b82c2cd144e2e880cb2) seems to have introduced the bug.

**Comment by stjepang** [comment]
Thank you for the report and investigating!

Can you verify whether https://github.com/stjepang/smol/pull/117 resolves the issue?

**Comment by nmccarty** [comment]
It resolves the issue for me, both on my "minimal" example as well as in the full test suite it came from.
Thank you!

**Comment by stjepang** [comment]
Published v0.1.6 with the bugfix.
