### ISSUE TITLE
Allow for multiple work stealing executors

### ISSUE THREAD

**Issue by PSUdaemon** [stjepang/smol#123]
It would be nice to be able to run multiple work stealing executors on different thread pools. For example, a thread pool per NUMA node. That way tasks (and heap data associated with them) would not cross NUMA node boundaries.

**Comment by stjepang** [comment]
I'm working on this :)

**Comment by ctiller** [comment]
This would be huge for us too... would like to be able to isolate different work sets to their own thread pools.

**Comment by stjepang** [comment]
Smol is now just a small wrapper around multitask: https://docs.rs/multitask

It should be pretty easy now to write custom executors or make multiple instances of them :)
