### ISSUE TITLE
Regression introduced after smol 0.1.8

### ISSUE THREAD

**Issue by almetica** [stjepang/smol#136]
I'm currently debugging a stalling testsuite of mine:
https://github.com/almetica/almetica/runs/701817775

The testsuite stalls as soon as the sqlx based async database abstraction is used (using smol by using async-std).

The last commit of smol where the testsuite didn't stall: 56e459e966a93f983482b9d556800a2f61a3567b

The first commit of smol where the testsuite stalls: d7b06dd6b0d01f405784077bd5e45ffffc0ad452

The Github Action tests run under Ubuntu linux, my local environment under windows. Both environments are showing the behavior.

I haven't tried to create a minimal example code to re-create the stalling yet, but will try soon. When pulling a trace of cargo while running the testsuite I can see that the thread only idles and does not poll anything when stalling.

**Comment by almetica** [comment]
I think d7b06dd is a red hering. That commit prevents even a simple database connection creation using sqlx to not function.

The problem also seems to be flaky in various degrees after 56e459e966a93f983482b9d556800a2f61a3567b.

What I can say (running under windows):

When running against async-std 1.6.0 / smol@ 56e459e966a93f983482b9d556800a2f61a3567 :
 * Tests never stall.

When running against async-std 1.6.0 / smol 0.10.0:
 * Running the tests in parallel stalls the tests 75% of the time.
 * Running the tests with only 1 test thread never stalls.

When running against async-std 1.6.0 / smol@ c311b6897fb7525ef876070d80f6ee375686b605 (current master):
 * Running the tests in parallel stalls the tests 100% of the time.
 * Running the tests with only 1 test thread also stalls 100% of the time.

I wasn't be able to reproduce the problem with a more stripped down code example yet.

**Comment by almetica** [comment]
Just for fun I tried the following:
Revert d7b06dd6b0d01f405784077bd5e45ffffc0ad452 on the current master c311b6897fb7525ef876070d80f6ee375686b605.

This fixes all stall issues I currently face, but increases the CPU consumption on idle again, since the main thread never idles (on Windows)...

![grafik](https://user-images.githubusercontent.com/50792179/82749690-36a56980-9dab-11ea-96fa-a3f297b9d511.png)

**Comment by sopium** [comment]
My guess, as current master behaves differently from 0.1.10: it could be (partially) because of similar issues to #131: some events are considered neither readable nor writable (after #127) and are simply ignored. Can you try the branch from #134 (on linux, since windows hasn't been fixed yet)?

**Comment by almetica** [comment]
@sopium I tested against the branch of #134 using ubuntu linux 20.04, but sadly that PR doesn't fix the stall.

**Comment by stjepang** [comment]
I'm unfamiliar with postgres and trying reproduce. I have this in my .env:

```
TEST_DATABASE_CONNECTION="postgres://stjepan:stjepan@192.168.1.1:5432"
```

However, tests hang at:

```
        let mut conn = PgConnection::connect(format!("{}/postgres", db_url)).await?;
```

What am I doing wrong?

**Comment by almetica** [comment]
@stjepang I think running a docker container may be easier, since you can easily re-create it. This is the script I use to create a postgres docker container:

```shell
#!/bin/bash

docker create \
  --name=postgres \
  -e TZ=Europe/Berlin \
  -e POSTGRES_USER=almetica \
  -e POSTGRES_PASSWORD=almetica \
  -e POSTGRES_DB=almetica \
  -e PGDATA=/var/lib/postgresql/data/pgdata \
  -p 5432:5432 \
  --restart unless-stopped \
  --shm-size=256MB \
  postgres:latest

docker container start postgres
```

Here's how I create the .env file:
```shell
echo "TEST_DATABASE_CONNECTION="postgres://almetica:almetica@127.0.0.1:5432"" >> .env
```

The tests should fail with an error if you can't connect to the database with the following error code: ```(os error 10060)```

If it only hangs, than you have successfully re-created the issue!

**Comment by stjepang** [comment]
I think I have identified the problem - wanna check if this PR fixes it? https://github.com/stjepang/smol/pull/143

What was happening is this: the reactor locks `sources` and then wakes wakers - however, a `Waker` is sometimes constructed by `waker_fn()` and that waker itself is the last reference to it - the `Arc` created by `waker_fn()` is dropped, and the closure passed to `waker_fn()` is dropped, but the closure contains an `IoEvent`, which contains an `Async<Notifier>`, and the `Async::drop()` attempts to lock `sources` again.

So a lock is attempted while it's already held by the same thread and therefore we get a deadlock.

**Comment by almetica** [comment]
@stjepang It seems to fix some problems, since I can run more tests before it stalls again, but it's still stalling when doing some tests with async database IO.

Tested under ubuntu linux 20.04 and windows by patching my ```Cargo.toml```:
```toml
[patch.crates-io]
smol = { git = "https://github.com/stjepang/smol", branch = "unlock-before-wake", optional = true }
```

**Comment by dignifiedquire** [comment]
Still hangs in a project of mine, trying to switch to sqlx and getting these hangs with smol. Tested with and without the `unlock-before-wake` branch.

**Comment by dignifiedquire** [comment]
Unable to reproduce this with the latest version of smol

**Comment by almetica** [comment]
Yes, with the latest version of smol and async-std the stalls are now fixed.
