### ISSUE TITLE
feature request: Async add method read_with_other and write_with_other

### ISSUE THREAD

**Issue by Sherlock-Holo** [stjepang/smol#139]
# Why

at normal, we want to use `Async<T>` do something, such as `read`, `write`, `connect` or `create`. All of them don't require another `Async<T>`, however sometimes we need another one, like `splice`, with `nix::fcntl::splice`
```rust
pub fn splice(
    fd_in: RawFd, 
    off_in: Option<&mut loff_t>, 
    fd_out: RawFd, 
    off_out: Option<&mut loff_t>, 
    len: usize, 
    flags: SpliceFFlags
) -> Result<usize>
```
if we use
```rust
let x = Async::new(tcp_stream);
let (pipe_r, pipe_w) = os_pipe::new();
set_non_block(pipe_r);

x.read_with(|x|{
    let err = fcntl::splice(x.as_raw_fd(), None, pipe_w.as_raw_fd(), None, 4096, flags);
    convert_err(err);
})
```
if we set both fd non-block, when `splice` returns `EAGAIN`, that maybe `x` is not readable, or pipe_w is not writable. The `read_with` only register `x` `EPOLLIN`, but we need register `pipe_w` `EPOLLOUT` too, but with `read_with`, we can't do this job.

# New method and enum
```rust
#[derive(Debug, Copy, Clone)]
enum Event<'a, T> {
    Readable(&'a Async<T>),
    Writable(&'a Async<T>),
    ReadableMut(&'a mut Async<T>),
    WritableMut(&'a mut Async<T>),
}

read_with_other<T, R>(&self, event: Event<'_, T>, op: impl FnMut(&T, Event<'_, T>) -> Result<R>) -> Result<R>

read_with_other_mut<T, R>(&mut self, event: Event<'_, T>, op: impl FnMut(&T, Event<'_, T>) -> Result<R>) -> Result<R>

write_with_other<T, R>(&self, event: Event<'_, T>, op: impl FnMut(&T, Event<'_, T>) -> Result<R>) -> Result<R>

write_with_other_mut<T, R>(&mut self, event: Event<'_, T>, op: impl FnMut(&T, Event<'_, T>) -> Result<R>) -> Result<R>
```

when op return `WouldBlock`, register self and another one in `Event` into epoll, that may fix the problem like `splice`.

If someone want do something with a lot of `Async<T>`, maybe we could add more new apis like
```rust
read_with_other<T, R>(&self, event: &[Event<'_, T>], op: impl FnMut(&T, &[Event<'_, T>]) -> Result<R>) -> Result<R>
```

**Comment by stjepang** [comment]
What if `Async` had the following methods?

```rust
async fn readable(&self);
async fn writable(&self);
```

Would that solve the problem?

**Comment by Sherlock-Holo** [comment]
yes it can solve problem

**Comment by Sherlock-Holo** [comment]
I create a PR to add these async functions, you can review it and help me make it good enough to merge :)

**Comment by stjepang** [comment]
Version 0.1.16 now has `Async::readable()` and `Async::writable()`.
