### ISSUE TITLE
is there anything like #[smol::main]?

### ISSUE THREAD

**Issue by jesse996** [stjepang/smol#140]
Is there anything like: #[async_std::main]?
if not,can i use #[async_std::main]?

**Comment by zicklag** [comment]
There actually is: https://github.com/wusyong/smol-potat. It would be good to have a link in the README and/or documentation. No problem either way, but I'm sure that the  project would appreciate the PR if you can spare the time to add the link. :smiley:

**Comment by zserik** [comment]
I think this issue is fixed and can be closed, or is there anything left to do?

**Comment by leo-lb** [comment]
https://github.com/stjepang/smol/commit/6a9216139d45f63248e716472a2f87ddc4b1f3e4
