### ISSUE TITLE
smol fails to build on OpenBSD (nix crate related issue)

### ISSUE THREAD

**Issue by nickpelone** [stjepang/smol#146]
Hey there! Excited to see this project.

It looks like it doesn't build on OpenBSD:

```
error[E0599]: no associated item named `EV_RECEIPT` found for struct `nix::sys::event::EventFlag` in the current scope
   --> src/reactor.rs:550:69
    |
550 |             let mut read_flags = EventFlag::EV_ONESHOT | EventFlag::EV_RECEIPT;
    |                                                                     ^^^^^^^^^^ associated item not found in `nix::sys::event::EventFlag`

error[E0599]: no associated item named `EV_RECEIPT` found for struct `nix::sys::event::EventFlag` in the current scope
   --> src/reactor.rs:551:70
    |
551 |             let mut write_flags = EventFlag::EV_ONESHOT | EventFlag::EV_RECEIPT;
    |                                                                      ^^^^^^^^^^ associated item not found in `nix::sys::event::EventFlag`

error[E0599]: no associated item named `EV_RECEIPT` found for struct `nix::sys::event::EventFlag` in the current scope
   --> src/reactor.rs:597:36
    |
597 |             let flags = EventFlag::EV_RECEIPT | EventFlag::EV_DELETE;
    |                                    ^^^^^^^^^^ associated item not found in `nix::sys::event::EventFlag`

error[E0599]: no variant or associated item named `EVFILT_USER` found for enum `nix::sys::event::EventFilter` in the current scope
   --> src/reactor.rs:630:53
    |
630 |             let event = KEvent::new(0, EventFilter::EVFILT_USER, flags, FFLAGS, 0, 0);
    |                                                     ^^^^^^^^^^^
    |                                                     |
    |                                                     variant or associated item not found in `nix::sys::event::EventFilter`
    |                                                     help: there is a variant with a similar name: `EVFILT_TIMER`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `smol`.
```

From the messages, it's missing some `EventFlag` and `EventFilter` items - [`EV_RECEIPT`](https://github.com/nix-rust/nix/blob/master/src/sys/event.rs#L93) for example has been excluded from `nix` for a while, even though it has since landed in OpenBSD. However, we don't have `EVFILT_USER` at all - so I dunno what to do or say there.

I guess the first one, the `EV_RECEIPT` thing - that's more to raise with `nix` maintainers, which I'll try to do next - but any thoughts on how to work around there being no `EVFILT_USER`?

**Comment by nickpelone** [comment]
I opened https://github.com/nix-rust/nix/pull/1252 over at the `nix` crate, and then building with those changes, it's just down to the `EVFILT_USER` issue:

```
error[E0599]: no variant or associated item named `EVFILT_USER` found for enum `nix::sys::event::EventFilter` in the current scope
   --> src/reactor.rs:630:53
    |
630 |             let event = KEvent::new(0, EventFilter::EVFILT_USER, flags, FFLAGS, 0, 0);
    |                                                     ^^^^^^^^^^^
    |                                                     |
    |                                                     variant or associated item not found in `nix::sys::event::EventFilter`
    |                                                     help: there is a variant with a similar name: `EVFILT_TIMER`

error: aborting due to previous error

```

I could look into what you're supposed to do on OpenBSD and offer a fix after my PR (hopefully) lands over at `nix`.

**Comment by nickpelone** [comment]
Doing some further digging, other things have had to do alternate, pipe-based implementations on platforms without `EVFILT_USER`: 

https://github.com/Thomasdezeeuw/gaea/issues/69
https://github.com/Thomasdezeeuw/gaea/commit/b359eb22238a20868b9e390c463aef2fa3f37673

I intend to try my hand at this and get a working `Reactor` on OpenBSD.

**Comment by dignifiedquire** [comment]
nix was replaced with custom syscalls on master, should male this easier to work with

**Comment by nickpelone** [comment]
It certainly builds and can do some basic async hello world stuff now! Thanks.

I'm going to do some more thorough testing and then if everything looks good I'll close this issue.

Peeked the PR, thanks for the work you did on this.

**Comment by nickpelone** [comment]
Sorry, I forgot to come back to this. With the new release that just uses `libc`, I am able to build `smol` / `async-std` / etc. If any runtime issues pop up, I'll file new issues.

Thanks!
