### ISSUE TITLE
Consider exporting and documenting the 'async_io::poll_future' function

### ISSUE THREAD

**Issue by zserik** [stjepang/smol#157]
I looked through the code of this crate and found the `poll_future` function inside `async_io.rs`. I copied it into code of mine (which already uses `smol` as async backend) and it seems to work (at least it compiles without errors and warnings, but I haven't tested it enough to be sure that it really works as expected in practice). The function seems to be useful to call `async` functions from `poll_*` implementations (`impl` `AsyncRead`, `AsyncWrite`, etc.), but I don't know about the general applicability of it for that use case.

**Comment by stjepang** [comment]
I think that would be a better fit for the `futures` crate. It is a function I've often wanted and need to implement myself every time :/

**Comment by zserik** [comment]
I think the most important restriction of the function is that the `Future` looses all internal state (internal to the future, not internal to `self`) on yield, which means all state which can't be recovered implicitly, but should be retained (= parameters of `fn poll_*` often shouldn't be retained, as they might change), must be exported/saved into `self`.

**Comment by zserik** [comment]
hm, I used it in [yz-encsess v2](https://github.com/YZITE/encsess2/tree/master/lib/src), but I'm not sure if my usage is correct (e.g. resilent and reentrant).
