### ISSUE TITLE
Scheduling looks unfair

### ISSUE THREAD

**Issue by polachok** [stjepang/smol#159]
Repro:

```rust
use std::net::{TcpStream, TcpListener};
use smol::{Async, Task};
use std::io::Error;

use futures_util::{select, AsyncWriteExt, AsyncReadExt};
use futures_util::future::{self, FutureExt};

async fn task(task_id: u32) -> Result<(), Error> {
    let listener = Async::<TcpListener>::bind("127.0.0.1:0")?;
    let addr = listener.get_ref().local_addr()?;
    println!("Listening on {}", addr);
    let accept = listener.accept();
    let connect = Async::<TcpStream>::connect(&addr);
    let (writer, reader) = future::join(accept, connect).await;
    let ((mut writer, _), mut reader) = (writer?, reader?);

    let mut buf = [0u8; 4];
    for i in 1..10_000_000u32 {
        let w = task_id.to_ne_bytes();
        select! {
            _ = writer.write(&w).fuse() => { }
            _ = reader.read(&mut buf).fuse() => { }
        }
        if i % 100_000 == 0 {
            println!("task {} processed {}", task_id, i);
        }
    }

    Ok(())
}

fn main() {
    smol::run(async {
        let t1 = Task::local(async {
            task(1).await.unwrap();
        });
        let t2 = Task::local(async {
            task(2).await.unwrap();
        });
        t1.await;
        t2.await;
    })
}
```

I would expect it to switch from t1 to t2 (or t2 to t1, depends on the run), but it doesn't until first one is complete.

**Comment by polachok** [comment]
So I straced it, what I see is (interesting part):
```
recvfrom(10, "\2\0\0\0", 4, 0, NULL, NULL) = 4
recvfrom(10, 0x55bb6674b960, 4, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
<- this is poll_read() / read_with_mut()
epoll_ctl(5, EPOLL_CTL_MOD, 10, {EPOLLIN|EPOLLRDHUP|EPOLLONESHOT, {u32=4, u64=4}}) = 0 <- this is source.readable() registering task
sendto(14, "\2\0\0\0", 4, MSG_NOSIGNAL, NULL, 0) = 4 <- always succeeds because tcp write buffer is huge
sendto(14, "\2\0\0\0", 4, MSG_NOSIGNAL, NULL, 0) = 4
recvfrom(10, "\2\0\0\0", 4, 0, NULL, NULL) = 4 <- this is poll_read() again, the reactor doesn't know if it's readable but we try it anyway and succeed (because we just sent some bytes in there)
```
It never gives up control to the reactor (no epoll_wait). My guess would be that it happens because read_with_*/write_with_* is optimistic and tries to perform read/write without actually checking if the source is readable/writable.

**Comment by rtyler** [comment]
I have witnessed similar behavior with a non-trivial async-std application. The solution that I found was to throw some `task::yield_now().await` calls  (async-std) in a couple of key places to ensure one task wouldn't dominate the runtime.

Unfortunately I wasn't able to file a bug here, but it _is_ reproducible with [the application](https://github.com/reiseburo/hotdog), but to reproduce it, requires some Docker containers spun up for some integration testing of the whole app. :frowning:

**Comment by zserik** [comment]
Does it change behavoir if `futures_util::join!` is used?

**Comment by bjornmolin** [comment]
I do also think it is the expected behaviour. Take a look at https://rust-lang.github.io/async-book/06_multiple_futures/02_join.html

**Comment by polachok** [comment]
@zserik no.

@bjornmolin how is this expected? It is not `t1.await; t2.await;`, tasks were spawned.

**Comment by asonix** [comment]
It's not an issue with awaiting task1 before task2. Since these tasks are spawned onto smol with Task::local, they should operate concurrently regardless of the order of the awaits. Further, spawning them at all doesn't change the outcome. An even simpler repro could exist by joining two calls to the `task` function. e.g.

```rust
fn main() {
  smol::run(future::try_join(task(1), task(2))).unwrap();
}
```
While both tasks should be polled concurrently task(1) completes it's iteration before task(2)'s iteration begins. Both futures print "Listening on" before task(1) starts it's iteration, so the problem is definitely that it's refusing to yield.

**Comment by zserik** [comment]
The following works as expected, but I explicitly needed to remove the `async` blocks around the `task(n)` calls...
```rust
use std::net::{TcpStream, TcpListener};
use smol::{Async, Task};
use std::io::Error;

use futures_util::{select, AsyncWriteExt, AsyncReadExt};
use futures_util::future::{self, FutureExt};

async fn task(task_id: u32) -> Result<(), Error> {
    let listener = Async::<TcpListener>::bind("127.0.0.1:0")?;
    let addr = listener.get_ref().local_addr()?;
    println!("Listening on {}", addr);
    let accept = listener.accept();
    let connect = Async::<TcpStream>::connect(&addr);
    let (writer, reader) = future::join(accept, connect).await;
    let ((mut writer, _), mut reader) = (writer?, reader?);

    let mut buf = [0u8; 4];
    for i in 1..10_000_000u32 {
        let w = task_id.to_ne_bytes();
        select! {
            _ = writer.write(&w).fuse() => { }
            _ = reader.read(&mut buf).fuse() => { }
        }
        if i % 100_000 == 0 {
            println!("task {} processed {}", task_id, i);
        }
    }

    Ok(())
}

fn main() {
    smol::run(async {
        let t1 = Task::blocking(task(1));
        let t2 = Task::blocking(task(2));
        future::join(t1, t2).await;
    })
}
```

**Comment by polachok** [comment]
Seems to work as expected with #151

**Comment by bjornSVT** [comment]
Ah interesting...I was way too fast in my conclusion and is obviously learning some good basic stuff :smile: 

It has something to do with what's in the task function since the code below is also working as you expected. 

```
use std::net::{TcpStream, TcpListener};
use smol::{Async, Task};
use std::io::Error;
use std::time::Duration;

use futures_util::{select, AsyncWriteExt, AsyncReadExt};
use futures_util::future::{self, FutureExt};

async fn task(task_id: u32) -> Result<(), Error> {
    println!("Task start {}", task_id);
    async_std::task::sleep(Duration::from_secs(5)).await;
    println!("Task done {}", task_id);

    Ok(())
}

fn main() {
    smol::run(async {
        let t1 = Task::local(async {
            task(1).await.unwrap();
        });
        let t2 = Task::local(async {
            task(2).await.unwrap();
        });
        t1.await;
        t2.await;
    })
}
```

**Comment by bjornmolin** [comment]
Ah interesting...I was way too fast in my conclusion and is obviously learning some good basic stuff :smile: 

It has something to do with what's in the task function since the code below is also working as you expected. 

```
use std::net::{TcpStream, TcpListener};
use smol::{Async, Task};
use std::io::Error;
use std::time::Duration;

use futures_util::{select, AsyncWriteExt, AsyncReadExt};
use futures_util::future::{self, FutureExt};

async fn task(task_id: u32) -> Result<(), Error> {
    println!("Task start {}", task_id);
    async_std::task::sleep(Duration::from_secs(5)).await;
    println!("Task done {}", task_id);

    Ok(())
}

fn main() {
    smol::run(async {
        let t1 = Task::local(async {
            task(1).await.unwrap();
        });
        let t2 = Task::local(async {
            task(2).await.unwrap();
        });
        t1.await;
        t2.await;
    })
}
```

**Comment by rtyler** [comment]
@yoshuawuyts suggested I include some details of a problem I'm investigating here:

I am investigating a performance issue and it looks like what was previously parallel computation is now concurrent, and that's not desired (duh). 

```
+--------------------+                  +------------------------+
|                    |  channel.send()  |                        |
|   BufReader task   |                  |                        |
|   off TcpStream    +----------------->+ Worker task in loop w/ |
|                    |                  | channel.read()         |
+--------------------+                  |                        |
                                        |                        |
                                        +------------------------+
```

While developing, I added a `task::yield_now().await` into place after I `send` on an async-std channel, that seemed to make things seem more parallel, but that makes me think the application is still not properly parallelizing its execution of tasks on smol.

interestingly, running the same code on async-std 1.5.0 (no smol) and 1.6.0 (much smol) definitely shows different performance when I remove my yield_now hack.  With async-std 1.6.0 it seems that one task is dominating the reactor and never cooperates with a concurrent task, meaning the behavior is that the "TCP" buffer receives everything there is to receive, enqueues it in a channel, and once the TCP reads are done, then the consumer from that channel starts executing its runloop. In 1.5.0, those operations are interwoven.

this behavior is only reproducible when the data is streaming into the TCP connection, i.e. the BufReader.lines().next().await is returning a value on each iteration, if I have my test client pause for a moment between sending lines, then the 1.6.0-based version properly interleaves the tasks

**Comment by stjepang** [comment]
This is now solved by the latest version of `async-io`, which yields inside read/write operation with some small probability, thus preventing tasks from hogging the executor forever.
