### ISSUE TITLE
Bounded work-stealing executors

### ISSUE THREAD

**Issue by andrewwhitehead** [stjepang/smol#164]
For usage in a library, it would be nice to have the ability to create a local work-stealing executor that didn't automatically transfer tasks to the global injector, so that the executor can be dropped (or drained) and any associated resources are freed.

I'm thinking that a `run_bounded` (?) method could be added which took a reference to the WorkStealingExecutor to use, and `run` would become a simple wrapper around this method which passed in the global instance. An additional function would need to be exposed for creating a new WSE instance. From looking at the code I don't see any issues with this, but maybe there are other components that assume there can only be one instance?

**Comment by stjepang** [comment]
I'm working on this feature right now :)

**Comment by andrewwhitehead** [comment]
Excellent! `smol::pool()` maybe?

**Comment by stjepang** [comment]
This is now possible with `smol::run()` and `smol::block_on()`.
