### ISSUE TITLE
Network communication stucks when large arrays are transfered repeatedly

### ISSUE THREAD

**Issue by zenryaku** [stjepang/smol#168]
I found my network application stucks when using async-std v1.6.x which uses smol.
async-std v1.5.0 is fine, which does not use smol.
I converted my project to use smol directly, and the problem remained.

Then I wrote test programs to reproduce the problem.

* https://gitlab.com/kashiko/test-smol
* https://gitlab.com/kashiko/test-async-std

Each project compiles to two binaries `server` and `client`.
To reproduce the problem, first run `server` on a terminal
and then run `client` on another terminal.
The `client` sends arrays repeatedly to the `server`,
and the `server` echoes the arrays,
and the `client` receives the echoed arrays.
Communication logs are printed on both terminals.
At a point of the iteration, the network communication stucks when using smol.
When using async-std v1.5.0, the demonstration program works fine and the `client` exits.

Usage of the programs:

If `server` is invoked with no arguments, it listens 127.0.0.1:8080.
The server's socket address can be specified by the first argument.

If `client` is invoked with no arguments, it connects to 127.0.0.1:8080
and send arrays 32 times with increasing sizes.
The count of the iteration can be specified by the first argument,
and the server's socket address to connect can be specified by the second argument.

In my environment, iteration count 17 is sufficient to stuck.

**Comment by sopium** [comment]
Dup of #161? Should be fixed by #162.

**Comment by zenryaku** [comment]
@sopium Thanks!
The problem ceased by using your branch on #162.
So it should be dup.

**Comment by stjepang** [comment]
I have published version 0.1.13 with the fix. Let's close this if the problem is resolved :)

**Comment by zenryaku** [comment]
@stjepang Thank you. The problem is resolved.
