### ISSUE TITLE
AsyncWrite::poll_close should call the shutdown instead of flush?

### ISSUE THREAD

**Issue by optman** [stjepang/smol#173]
https://github.com/stjepang/smol/blob/69c04a9e42ff51a47e2e5b7886d3126f2a545645/src/async_io.rs#L538

`AsyncWrite::poll_close` should call `shutdown` instead of `flush`? Otherwise  it can't notify other end we have nothing to send.

I come across this issue when i split the `async_std::net::TcpStream` into `ReadHalf` and `WriteHalf`, then there is noway to call `TcpStream::shutdown` again, only can be done in `AsyncWrite::poll_close`.

**Comment by sopium** [comment]
Well you don't need to call `split` on TcpStream, because `AsyncRead` / `AsyncWrite` are implemented for `&Async<TcpStream>` too. You can use `&Async<TcpStream>` or `std::sync::Arc` or this [`Arc`](https://docs.rs/async-dup/1.1.0/async_dup/struct.Arc.html). With these you still have access to the `shutdown` method.

(This is just FYI. It might still make sense to change `poll_close` to `shutdown` the stream regardless.)

**Comment by optman** [comment]
I  am concat two streams in two futures. To avoid two mutable borrow, it need to be split into reader and writer.  

`
async fn concat_stream(src : TcpStream, dst : yamux::Stream){
    let (mut src_reader, mut src_writer) = src.split();
    let (mut dst_reader, mut dst_writer) = dst.split();

    let a= async {
        io::copy(&mut src_reader, &mut dst_writer).await;
        dst_writer.close().await
    };

    let b= async {
        io::copy(&mut dst_reader, &mut src_writer).await;
        src_writer.close().await
    };

   future::try_join(a, b).await;
`
yamux::Stream  already works as expected, but TcpStream is not.

use min_specialization to fix it.

`
impl AsyncWrite for &Async<TcpStream>
{
    fn poll_close(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<io::Result<()>> {
        poll_future(cx, self.write_with(|io| io.shutdown(Shutdown::Write)))
    }
}
`

**Comment by sopium** [comment]
What exactly is `TcpStream` in your code? If it's smol's `Async<TcpStream>`, I think you can do this (untested):

```rust
let a = async {
    io::copy(&src, &mut dst_writer).await;
    dst_writer.close().await
};

let b = async {
    io::copy(&mut dst_reader, &mut &src).await;
    src.get_ref().shutdown(Shutdown::Write)
};
```

**Comment by stjepang** [comment]
I think we should fix this and shutdown the stream when `poll_close()` is called.

**Comment by optman** [comment]
To be clear, i am using the async_std::TcpStream, there is no way to access the underlying Async<TcpStream>.

**Comment by sopium** [comment]
> To be clear, i am using the `async_std::net::TcpStream`, there is no way to access the underlying `Async<TcpStream>`.

It should work too, because `Read` and `Write` are implemented for `&TcpStream`: https://docs.rs/async-std/1.6.2/async_std/net/struct.TcpStream.html#impl-Read-1

There is also a `Clone` implementation, so you don't need any `Arc` even if you need owned clones.

**Comment by optman** [comment]
Well, `async_std::net::TcpStream` has a `Clone` implementation, that is good. Then there is no need to `split`,  use `clone` instead, then call `TcpStream::shutdown`, the problem solved.

But not every stream can be cloned, and different concrete stream have different shutdown method name.  What if i have a more generic concat function.

```rust
async fn concat_stream<T1, T2>(x : T1, y : T2) where
    T1 : AsyncRead + AsyncWrite,
    T2 : AsyncRead + AsyncWrite,
{
}
```
The split version still works, but the clone version does not.

**Comment by stjepang** [comment]
This is now fixed in async-io: https://github.com/stjepang/async-io
