### ISSUE TITLE
Executor state visibility layer

### ISSUE THREAD

**Issue by ar3s3ru** [stjepang/smol#181]
For application visibility, especially in the case of microservices using `smol` as an async runtime, it might be useful to track the current executor state (number of waiting tasks, number of threads, etc.)

This information appears to be present in `blocking::State`: https://github.com/stjepang/smol/blob/84bbdd03cd686fae3031d0cd50f11f55f53b4052/src/blocking.rs#L47-L60

* Could we expose accessors to those properties?
* Could we include an additional feature flag to expose an OpenCensus view keeping track of these metrics? Or is it better to write an external component for this?

**Comment by stjepang** [comment]
I suggest looking into this executor crate. It should be easy to add custom statistics to it:

https://docs.rs/multitask

**Comment by ar3s3ru** [comment]
Hey @stjepang, thanks for the answer.

Why do you point to `multitask` crate? I don't see it being used in `smol`.

**Comment by stjepang** [comment]
See #188 :) I’m breaking smol into three smaller crates: in the end smol will be just a thin wrapper around multitask. And multitask makes it easy to write custom executors or add counters/statistics.

**Comment by ar3s3ru** [comment]
Oh, think I missed that PR. Thanks for pointing that out.

I'll take a look there and eventually open an issue/PR in the repo :+1:
