### ISSUE TITLE
piper reference in doc

### ISSUE THREAD

**Issue by keepsimple1** [stjepang/smol#186]
For example, this one:
https://github.com/stjepang/smol/blob/84bbdd03cd686fae3031d0cd50f11f55f53b4052/src/async_io.rs#L45

As `piper` has been [deprecated](https://docs.rs/piper/0.1.3/piper/), should the example be updated? (In this case, should we use std `Arc` or some other crate?).

**Comment by keepsimple1** [comment]
I guess it would be replaced by [async_dup Arc](https://docs.rs/async-dup/1.2.1/async_dup/struct.Arc.html)

**Comment by stjepang** [comment]
Piper is gone in #188
