### ISSUE TITLE
How do You Pronounce Smol?

### ISSUE THREAD

**Issue by zicklag** [stjepang/smol#189]
Is it pronounced like "small" or with a long ō sound like "smōle".

**Comment by rtyler** [comment]
[Smol](https://knowyourmeme.com/memes/smol) :smile_cat:  (small)


Unless of course @stjepang is a non-traditional meme user

**Comment by zicklag** [comment]
I thought that it may be something like meme related. I'm not real meme savvy. :wink:

**Comment by stjepang** [comment]
My "favorite" pronunciation I heard was es-em-oh-el 🤦🏻‍♂️

**Comment by zicklag** [comment]
OK, I think I'm satisfied with the answers. :)
