### ISSUE TITLE
Ability to control number of threads in smol 0.2

### ISSUE THREAD

**Issue by L1AN0** [stjepang/smol#194]
Currently when  using `smol::Task` (version 0.2) num cpu of threads will be created. But we want to control the number of threads in certain scenarios.

**Comment by stjepang** [comment]
With smol 0.3 it's easy enough to create a custom function for starting an executor with arbitrary number of threads:

```rust
fn run<T>(num_threads: usize, future: impl Future<Output = T>) -> T {
    // A channel that coordinates shutdown when the main future completes.
    let (trigger, shutdown) = unbounded::<()>();
    let future = async move {
        let _trigger = trigger; // Dropped at the end of this async block.
        future.await
    };

    let ex = Executor::new();
    let local_ex = LocalExecutor::new();
    Parallel::new()
        .each(0..num_threads, |_| ex.run(shutdown.recv()))
        .finish(|| ex.enter(|| local_ex.run(future)))
        .1
}
```

I wonder if it would be useful to perhaps use `SMOL_THREADS` environment flag for easier testing/debugging?

**Comment by L1AN0** [comment]
Thanks. That's easy enough. It will be great if this example is in the docs or examples.

As for the `SMOL_THREADS` environment, how about allowing the user to modify the default global executor?

**Comment by stjepang** [comment]
There is now a choice between block_on() and run(), as well as SMOL_THREADS environment variable.
