### ISSUE TITLE
Failing other-runtime example with smol 2.0

### ISSUE THREAD

**Issue by ansrivas** [stjepang/smol#196]
Hi @stjepang , thank you for all the work.

I noticed that now that crates have been modularized, we have a feature flag `tokio02` in smol. But the example is using the `blocking` crate.

With the new change, we will need to wrap [this part](https://github.com/stjepang/smol/blob/b3005d942040f68f30ad84b6f8f1621ebaf9d753/examples/other-runtimes.rs#L32-L43) of the code inside `smol::Task::spawn(async {...})` and enable `tokio02` for it to execute? ( Please correct me if I am wrong )

```
        Task::spawn(async {
            // Sleep using tokio (the `tokio02` feature must be enabled).
            let start = Instant::now();
            println!("Sleeping using tokio...");
            tokio::time::delay_for(Duration::from_secs(1)).await;
            println!("Woke up after {:?}", start.elapsed());
            // Make a GET request using reqwest (the `tokio02` feature must be enabled).
            let resp = reqwest::get("https://www.rust-lang.org").await.unwrap();
            let body = resp.text().await.unwrap();
            println!("Body from reqwest: {:?}", body);
        })
        .await;
```

**Comment by ansrivas** [comment]
Thank you :)

**Comment by stjepang** [comment]
In smol 0.3, you can replace `block_on()` with `smol::run()`.

If you want to *just* block on a future/stream/IO, there are:
* `smol::future::block_on()`
* `smol::stream::block_on()`
* `smol::io::BlockOn`
