### ISSUE TITLE
Is it allowed to use RawFd of Async<UdpSocket> ?

### ISSUE THREAD

**Issue by keepsimple1** [stjepang/smol#197]
I'm using smol `Async<UdpSocket>` and wanted to use `sendmsg` from `nix` crate (`nix::sys::socket::sendmsg`) in Linux. I'm calling:

```
let fd = sock.as_raw_fd();   // sock is &Async<UdpSocket>
<snip>
match sendmsg(fd, &[iov], &ctrl_msgs, MsgFlags::empty(), Some(&addr)) {
```

This part of code works in a test I've added into `nix` using `std::net::UdpSocket`, but fails when integrating with smol `Async<UdpSocket>`.  Is it allowed to use `RawFd` of `Async<UdpSocket>`  ? 

The error I got is from calling `sendmsg` is:  `EIO: I/O error` .

**Comment by stjepang** [comment]
Yes, this should work, you just need to keep in mind that `Async` puts the socket in non-blocking mode, so if the `sendmsg` operation would block, it will error with EWOULDBLOCK. In case of that error, you would then do `.writable().await` to wait until the socket becomes writable again and then try again.

Or, an even nicer solution would be to use `.write_with(|sock| ...).await`, which will wait and retry for you:

```rust
let res = sock
    .write_with(|sock| {
        sendmsg(
            sock.as_raw_fd(),
            &[iov],
            &ctrl_msgs,
            MsgFlags::empty(),
            Some(&addr).map_err(io_err),
        )
    })
    .await;
```

See this example for how to read using `nix`: https://github.com/stjepang/smol/blob/b8f5364e6c1d95dbc09560f91c9de6639e8e5518/examples/linux-timerfd.rs#L33

**Comment by keepsimple1** [comment]
Thanks a lot for the details. After more testing and digging deeper, it seems not a `smol`, or `nix` or Rust issue.  The test only succeeded with local server using loopback interface. The issue is with the underlying wireless driver / hardware when testing with remote server. Will close this one.
