### ISSUE TITLE
Is it possible to run a task and join it later?

### ISSUE THREAD

**Issue by keepsimple1** [stjepang/smol#203]
In `std::thread`,  we can do `thread::spawn` to run the thread immediately and get a `JoinHandle` to join the thread at a later time. Is it possible to do similar things with `smol::Task`?  

It seems that I can either do `task.await` to run it immediately and wait it to finish,  or do `detach()` but cannot join/wait it at a later time.  But I cannot find a way to run the task immediately and join it at a later time (without wrapping it in a thread). Maybe I missed something obvious or is it not supported? Thanks.

**Comment by stjepang** [comment]
That’s exactly how tasks work. They are scheduled to run immediately even if you don’t poll the Task handle.

**Comment by keepsimple1** [comment]
Thanks! Sorry I mis-interpreted my test program.
