### ISSUE TITLE
Explicit `smol::run_smol` and `smol::run_tokio`

### ISSUE THREAD

**Issue by joshtriplett** [stjepang/smol#204]
When building multiple crates within a workspace, if one crate depends on `smol` with the `tokio02` feature and another crate doesn't need the `tokio02` feature, a workspace-wide build will build `smol` once, *with* the `tokio02` feature, and use it for both dependencies. This means the crate that doesn't need tokio gets it anyway, which slows down startup, increases code size, and similar.

Would you consider adding a method `smol::run_smol`, which *always* runs just the smol runtime without tokio compatibility, even if compiled with `tokio02`? And a method `smol::run_with_tokio`, which only exists if you build with `tokio02` but which explicitly declares the requirement for tokio compatibility in-code? `smol::run` could then just call one or the other of those depending on the `tokio02` feature.

**Comment by stjepang** [comment]
There isn't a `tokio02` feature flag anymore, but I made this crate for easier compatibility with tokio: https://github.com/stjepang/async-compat

**Comment by joshtriplett** [comment]
@stjepang That completely addresses the use case that originally motivated me to file this issue, thank you!
