### ISSUE TITLE
Publish 1.0

### ISSUE THREAD

**Issue by stjepang** [stjepang/smol#206]
I'm considering publishing version 1.0 of smol and other libraries that are still at 0.x:

- smol
- polling
- async-executor
- async-io
- blocking
- async-process

The API changes have been slowing down, and I feel like we're very close to the point where no breaking changes will be needed in the foreseeable future. I have no breaking changes in mind before 1.0 - all these crates would just get version bumps and that's it.

I'm opening this issue to ask everyone for opinions. Now is a great chance to voice concerns or request breaking changes, if you'd like to see any :)

**Comment by serzhiio** [comment]
Let's go stable!

**Comment by stjepang** [comment]
Published v1.0 for smol and all the remaining libraries!!
