### ISSUE TITLE
Make default Executor replaceable

### ISSUE THREAD

**Issue by Keruspe** [stjepang/smol#207]
#206 led me to thinking about this.

Starting with this in mind:
- the part of smol which is the most subject to debate lately is the Executor
- having the one Executor to please everyone is not an easy task, thus the recommendation to build your own
- sharing an Executor with other crates can be handy if you want to avoid having several separate thread pools

What would you think of making the default global executor configurable?
Let's name the current default Executor `DefaultExecutor` for convenience.
By default, calling `smol::spawn` would spawn the task inside this `DefaultExecutor` after having lazyly created it on first call.
What if we could replace this lazy init with an explicit init, like the ones we have for the logging system?

We would then be able to call `my_custom_executor::try_init().expect("there's already an executor in place")` at the beginning of the program, and `MyCustomExecutor` would be used instead of `DefaultExecutor`

**Comment by stjepang** [comment]
The purpose of the default executor (the one used by `smol::spawn()`) is for use in trivial programs and tests, but not in 'real' programs or libraries. Maybe I should put a more visible note saying "don't use `smol::spawn()` unless you need a dumb throwaway executor" :)

As you have pointed out, it's impossible to please everyone with one executor. I do *not* want to share the `smol::spawn()` executor with other crates for the simple reason that it was not designed for that. At the same time, I *do* think the idea of building a common executor shared by libraries is a worthwhile idea.

`my_custom_executor::try_init()` sounds good to me, but I hope that kind of universal executor would be a community-wide effort, perhaps something that will eventually be included in the standard library. I just think such an executor is outside the scope of smol right now. And if we pursued that idea within smol, we would almost surely want to change something about it in the future, which would clash with the plan to publish smol 1.0 soon.

So I'd be more open to exploring this in a new crate and then seeing how it pans out. What do you think?

**Comment by stjepang** [comment]
Closing since it's unlikely we'll make any changes to the smol executor at this point.
