### ISSUE TITLE
new executor's spawn semantics differ from other runtimes?

### ISSUE THREAD

**Issue by ian-p-cooke** [stjepang/smol#208]
I'm not sure if I was doing something wrong but it seemed like the new (0.4) Executor's spawn only schedules a future to be polled later and doesn't actually poll it.  That's different than every other runtime's `spawn` method.

What I did:

1. create a new executor
2. stick it in a global static OnceCell
3. in library code use that executor's spawn method
4. .await the returned task

the result was that the .await hung forever while I would expect the executor to poll the spawned future until ready and then my await would return.

I looked at the implementation of `smol::spawn` and you're doing something similar but you run a future that never completes in its own thread.  Is this what you have to do to start an Executor?  
```Rust
async_io::block_on(GLOBAL.run(future::pending::<()>()))
```
I can kind of understand that but it's different than other runtimes' executors and if that's the intended behavior then spawn should probably note that in the docs.  as it is now it's more of a 'schedule' then a 'spawn'.

**Comment by stjepang** [comment]
Your understanding is correct - `Executor` is an 'inert' type and does nothing on its own unless you call `tick()` or `run()`. I agree the documentation should be better. Will spend some time tomorrow on improving them...
