### ISSUE TITLE
Compilation error in async-fs on Windows

### ISSUE THREAD

**Issue by mjaakkol** [stjepang/smol#209]
I develop my stuff on Windows and MacOS and with the latest update Windows side started to cause troubles when pulling in async-fs. I was wondering if anybody else has seen this.

error[E0053]: method `security_qos_flags` has an incompatible type for trait
    --> C:\Users\XXXX\.cargo\registry\src\github.com-1ecc6299db9ec823\async-fs-1.3.0\src\lib.rs:1465:5
     |
1465 |     fn security_qos_flags(&mut self, flags: u32) -> &mut Self {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::fs::OpenOptions`, found struct `OpenOptions`
     |
     = note: expected fn pointer `fn(&mut OpenOptions, _) -> &mut std::fs::OpenOptions`
                found fn pointer `fn(&mut OpenOptions, _) -> &mut OpenOptions`

**Comment by stjepang** [comment]
This is really strange. What is your `rustc --version`?

**Comment by mjaakkol** [comment]
I was using the previous version 1.45.2 and when updating (was keeping my
Windows the same as there was some issues reported) things started to work.
It looks like this is on me. I'll close the issue.

**Comment by Geobert** [comment]
I've encounter this as well, which minimum version of rust do we need?

**Comment by stjepang** [comment]
@Geobert 1.46.0

**Comment by stjepang** [comment]
The PR that fixed this in the standard library: https://github.com/rust-lang/rust/pull/74074
