### ISSUE TITLE
Wrapping std::io::{Read, Write}

### ISSUE THREAD

**Issue by dignifiedquire** [stjepang/smol#22]
Currently `Async` supports wrapping things that can be converted pollable resources. In `async-native-tls` there is an adapter transforming a resource taht is only `std::io{Read|Write}` into `AsyncRead|Write`.

I wonder if this could be improved on, cleaned up and possibly put into here, allowing resources that are not pollable, to be wrapped easily.

Ref: https://github.com/async-email/async-native-tls/blob/master/src/std_adapter.rs

**Comment by stjepang** [comment]
This also reminds me of `futures::io::AllowStdIo`. Perhaps it would be a good addition to `futures`?

**Comment by stjepang** [comment]
Closing this issue - I think this should ideally live in some other crate.
