### ISSUE TITLE
illumos support

### ISSUE THREAD

**Issue by stjepang** [stjepang/smol#32]
Hi @pfmooney, hope you don't mind this mention - thought you might be interested! I have added support for illumos in this runtime by using `epoll` the same way it is used on Linux/Android.

I think the only missing piece right now is support for illumos in the `nix` crate - as soon as that step is done, I believe `smol` should *just work* on illumos. Do you perhaps know if there are any plans for adding illumos support to `nix`?

**Comment by pfmooney** [comment]
We've been wandering around the Rust countryside, looking for platform-related foundational crates which are featured heavily as dependencies.  On first glance, it looks like `nix` could fall into that category, but the lift to enable illumos support is more significant that some of the other crates so far.  I'll look into what all would be required for support there.
