### ISSUE TITLE
Better security practices on certificates

### ISSUE THREAD

**Issue by stjepang** [stjepang/smol#34]
As pointed out [here](https://www.reddit.com/r/rust/comments/g917ad/smol_stjepang_a_small_and_fast_async_runtime_for/foqn1y5/), we should not advise users to import the certificate into their browsers. It would be much better to generate them on their own.

Suggestions on what we should do here more concretely? I wonder if it'd be okay to keep the certificate for examples like tls-client.rs and tls-server.rs, but advise not using them for any HTTPS example.

**Comment by leo-lb** [comment]
Don't encourage them to add certificates to their browsers but you can warn them about the security notice that will show and offer them to dismiss it because it's self signed, and browsers handle that their own way. It's certainly not a good idea to distribute certificates in the git repository. But it should be obvious to everyone that these are examples and the certificates shouldnt be used anywhere else.

**Comment by stjepang** [comment]
@leo-lb This does not seem to work for me because it crashes the HTTPS server:

```
$ cargo run --example async-h1-server
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `/home/stjepan/work/smol/target/debug/examples/async-h1-server`
Listening on http://127.0.0.1:8000
Listening on https://127.0.0.1:8001
Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1535:SSL alert number 46

Caused by:
    error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1535:SSL alert number 46
```

**Comment by Shnatsel** [comment]
> Perhaps I should use some kind option in native-tls to accept insecure connections.

This is also not a great thing to do in examples, as people may copy-paste them and assume they would work. I'd prefer to include instructions for generating your own certificate in README for TLS because you'll likely have to do that for real use anyway, so you might as well show how to do that in the example. And if you copy-paste the example with minimal understanding, you're still secure.

**Comment by leo-lb** [comment]
> @leo-lb This does not seem to work for me because it crashes the HTTPS server:
> 
> ```
> $ cargo run --example async-h1-server
>     Finished dev [unoptimized + debuginfo] target(s) in 0.10s
>      Running `/home/stjepan/work/smol/target/debug/examples/async-h1-server`
> Listening on http://127.0.0.1:8000
> Listening on https://127.0.0.1:8001
> Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1535:SSL alert number 46
> 
> Caused by:
>     error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../ssl/record/rec_layer_s3.c:1535:SSL alert number 46
> ```
> 
> The TLS connection is not established. Perhaps I should use some kind option in native-tls to accept insecure connections.

It should never crash the server, the server isnt aware of the client's trusted CA list.

**Comment by leo-lb** [comment]
> > Perhaps I should use some kind option in native-tls to accept insecure connections.
> 
> This is also not a great thing to do in examples, as people may copy-paste them and assume they would work. I'd prefer to include instructions for generating your own certificate in README for TLS because you'll likely have to do that for real use anyway, so you might as well show how to do that in the example. And if you copy-paste the example with minimal understanding, you're still secure.

This would be about the server, not the client. It has no security implications to use a self-signed certificate on a server, what matters is how the client validates it.

**Comment by stjepang** [comment]
Ah, I think I get it now - if establishing a TLS connection fails, the server should just fall back to regular HTTP. I will push a fix soon... :)

**Comment by leo-lb** [comment]
@stjepang It can't, if the client requests TLS and that fails then it fails the request entirely. What you should do is have the ability to load untrusted certificates on the server side by plugging that feature into native-tls or whatever, and if the client is a browser, they can bypass the warning, and for the Rust HTTP over TLS example, you can choose to trust that arbitrary certificate by comparing fingerprints or something. E.g. read the trusted certificate file from disk, extract fingerprint, compare with TLS server certificate fingerprint, and if it matches establish TLS session

**Comment by stjepang** [comment]
@leo-lb When you dismiss the security notice in the browser, the browser will not even request TLS - it just uses plain HTTP even if the address starts with `https://`.

What seems to work for me is the following:

* If connecting to localhost:8000, serve requests.
* If connecting to localhost:8001, establish TLS and serve requests.
  * If establishing TLS fails, just go on and serve requests over the same stream.

**Comment by leo-lb** [comment]
@stjepang When you dismiss the security notice in the browser it does use TLS, it just decides to exceptionally trust a server certificate it would otherwise not because it's not signed by a trusted public CA

That looks like a bug with security implications if that's what it does, what client are you using for this test? Browser or Rust?
It's possible the error is thrown after an actual successful TLS session is established.

**Comment by apiraino** [comment]
> Suggestions on what we should do here more concretely? I wonder if it'd be okay to keep the certificate for examples like tls-client.rs and tls-server.rs, but advise not using them for any HTTPS example.

@stjepang Would a tool like this MkCert work to create own self-signed SSL certs?
(that's what I use sometimes)

https://github.com/FiloSottile/mkcert

**Comment by stjepang** [comment]
@apiraino Probably - I'll admit I'm not super familiar with certificates :)

Help would be appreciated here. What's the best way to generate some throwaway cetificates for testing, i.e. what's the "go-to" tool for that? Is it mkcert?

**Comment by leo-lb** [comment]
@stjepang There isnt really a go-to tool.. managing a CA is complicated. There's also this: https://github.com/OpenVPN/easy-rsa

**Comment by leo-lb** [comment]
@stjepang I'd suggest keeping things as they are right now and just stop advising adding that certificate to the trusted certificates database but instead manually trust it within the Rust client and tell people to dismiss the security warning in their browser.

**Comment by alexeldeib** [comment]
> This does not seem to work for me because it crashes the HTTPS server

This was a minor issue with the async-h1-server example, you can see it in https://github.com/stjepang/smol/pull/40. I also tweaked the phrasing in the docs a bit, but need to check the other examples to make sure that's accurate.

**Comment by stjepang** [comment]
This is now resolved. Thanks everyone for suggestions and PRs!! :)
