### ISSUE TITLE
Add Link To Blog Post: "Why I'm Building a New Async Runtime?"

### ISSUE THREAD

**Issue by zicklag** [stjepang/smol#38]
Hey there, I just found this project and I also happened to follow your GitHub user page to your blog and find the [post](https://stjepang.github.io/2020/04/03/why-im-building-a-new-async-runtime.html) about it as well. I was thinking that it would be great to link to that post from the README because it gives some great context on "yet another executor" and helped me realize why I would be interested in using it and what the motivation for its design was.

**Comment by stjepang** [comment]
Added a link to the readme. :)
