### ISSUE TITLE
Channel which can be seamlessly used with async and sync

### ISSUE THREAD

**Issue by tekjar** [stjepang/smol#4]
I'm really liking this pattern of using same types in both sync and async world. Reduces the sync/async friction to some degree in my opinion.

```rust
    let socket = Async::<TcpStream>::connect("127.0.0.1:8080").await?;
```
 Along the same lines, is it possible to have channel `Sender` and `Receiver` that can be easily used in both async and sync ecosystems. 

In the projects I'm working on, some threads are synchronous and some are async. I'm using tokio/futures channels to communicate between these. While using tx or rx in a synchronous thread,  I either use futures executor or wrap the function with `tokio::main` (even though the code is completely synchronous except for channel) and do `tx.send().await`. I'm not sure of the extra perf costs due to this while sending data at a very high frequency, it feels the async/sync boundaries I'm trying to maintain are shattered.

Is there a way to create channel which can be easily converted into async like this?

```rust
    let (tx, rx) = channel::<i32>();

   let tx = tx.async(); 
   let rx = rx.async();
```

**Comment by stjepang** [comment]
No, but it's easy to use async channels as sync channels by wrapping their operations into `block_on()`. Would that be an acceptable solution, what do you think?

**Comment by tekjar** [comment]
Yeah. It's very easy. I'm mostly talking about clean boundaries between async and sync world I guess. In a project where I'm using both crossbeam-channel and tokio-channel, I had to explain (multiple times to people who are new to async) why one channel uses `block_on` while the other doesn't. 

I thought sync first types which can be converted to async would solve these issues (as that is the direction in which people learn and projects move usually IMO). I think [flume receiver](https://docs.rs/flume/0.7.1/flume/struct.Receiver.html#implementations) is trying to do something along these lines. Also probably I'm being too pedantic :). Please feel free to close this if this not the direction you like

**Comment by stjepang** [comment]
I think the most difficult part here will be coming up with an API that is not too easy to misuse. In particular, It should not be tempting to block in async code - that must not happen by accident.

**Comment by stjepang** [comment]
We now have: https://docs.rs/async-channel
