### ISSUE TITLE
Tests don't run when cross compiling

### ISSUE THREAD

**Issue by leo-lb** [stjepang/smol#50]
```
     Running /target/powerpc64-unknown-linux-gnu/debug/deps/smol-4374c813ff2504f9

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
https://github.com/stjepang/smol/pull/40/checks?check_run_id=624277323#step:6:43

It's the same for every target platform.

Does the cross setup also includes qemu for usermode binary translation?

It's either that or we try to get runners for every architecture, which is feasible, I have a machine with an IBM POWER CPU at home on which I can run VMs of both big endian and little endian at the same time.

Travis also has powerpc64le runners, see: https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system

Github Actions does not have anything else than x86 for now. We might want to go hybrid with CI and start testing on arm and ppc64le natively with Travis.

**Comment by stjepang** [comment]
We run tests on android through qemu: https://github.com/stjepang/async-io/blob/master/.github/workflows/cross.yaml

Other platforms don’t seem to be supported by cargo-cross, but I think this is good enough.
