### ISSUE TITLE
Write unit tests to improve coverage

### ISSUE THREAD

**Issue by stjepang** [stjepang/smol#52]
Right now, the reported coverage on the badge in readme is 31%. Let's get it to 100%!

**Comment by stjepang** [comment]
PRs are welcome! If you'd like to contribute, this is an easy way to get started :)

**Comment by wusyong** [comment]
Wrote a few tests and run them a bit, I realized there are way too many branch conditions need to cover. Maybe we should disable [branch info](https://github.com/stjepang/smol/blob/master/.github/actions-rs/grcov.yml#L1)? What we want to make sure is line and function coverage are good enough. Trying to satisfy all is not practical imho.

**Comment by stjepang** [comment]
@wusyong That sounds reasonable - I think covering all branches is a bar too high.

**Comment by tshepang** [comment]
Another way to look at it is for 31% not be seen as bad, as in there is no need to get to 100%. That is, it's good to know that some branches are not covered. Does the service make it easy to see non-branch coverage results?

**Comment by wusyong** [comment]
@tshepang I think you are right. It just confused me when I added a test but the rate becomes lower because of more branch misses. Configure this should be easy anyway. I guess this comes down to what's the goal for the code coverage rate we are going to show (line/branch/path).

**Comment by stjepang** [comment]
Unit tests have moved into the smaller subcrates. See #188
