### ISSUE TITLE
Question about File

### ISSUE THREAD

**Issue by oblique** [stjepang/smol#61]
Why do you suggest to not use `Async<File>`? I'm actually using it for `/dev/ptmx` (https://github.com/oblique/sktsh).

Should I wrap it to another struct and use `libc::read`/`libc::write` directly?

**Comment by stjepang** [comment]
`Async` can only be used with things that are compatible with epoll/kqueue/wepoll.

If you're opening a special kind of file that *is* compatible, then it should work perfectly fine! But in general, regular files are not pollable (although they would work with io_uring).

I would suggest to use `smol::reader()` and `smol::writer()` instead.

**Comment by leo-lb** [comment]
Hello there!
Asynchronous filesystem operations currently don't have good kernel support across platforms, runtimes like tokio or async_std actually provide wrappers to blocking filesystem operations executed in a thread pool.
With smol you can simply do that as well, take your blocking filesystem operations and run them with smol's blocking executor.

**Comment by leo-lb** [comment]
@stjepang Well you rushed me there!

**Comment by oblique** [comment]
The reason I was hesitant to use smol::reader/smol::writer was an issue that I had with UNIX special files when I used async-std (https://github.com/async-rs/async-std/issues/724) because it was caching read/write operations.

As I understood smol::reader is doing something similar, which will cause misbehavior when it is used with `/dev/net/tun`.

Anyway, both cases that I'm going to use `Async<File>` (`/dev/ptmx` and `/dev/net/tun`) are special files that are supported by epoll.

Thanks for having a way to register a RawFd in reactor. I really like smol.

**Comment by zicklag** [comment]
Thanks for the responses @stjepang  and @leo-lb! I had the same question. That is something that I would have appreciated a note in the docs for.

I looked at that "don't use with File" note and thought, "hmm, I have to use a reader/writer wrapper around a synchronous file operation with smol? Tokio and async-std don't have you do that.", but in fact, Tokio and async-std are implemented the same way, it is just more invisible.

---

BTW I'm really loving the way that smol helps you "Asyncify" stuff. It is really promising and I can't believe that you can embed Tokio in it seamlessly! I'm going to be testing smol out in the [maxim](https://github.com/katharostech/maxim) actor framework. :smiley:
