### ISSUE TITLE
better doc about single-thread executor and multi-thread executor

### ISSUE THREAD

**Issue by Sherlock-Holo** [stjepang/smol#63]
Should we document it:
If we want to run a single-thread executor, just use
```rust
smol::run(async { ... })
```

If we want to run multi-thread executor, the better usage is
```rust
thread::spawn(smol::run(futures::future::pending::<()>()));
thread::spawn(smol::run(futures::future::pending::<()>()));
thread::spawn(smol::run(futures::future::pending::<()>()));
// write n times if you want n threads in executor

smol::block_on(async { ... })
```

**Comment by stjepang** [comment]
This is documented on the function `run()`: https://docs.rs/smol/0.1.4/smol/fn.run.html#examples

Suggestion on where else we should document this?

**Comment by pkorotkov** [comment]
@stjepang Maybe, outline a dedicated section "Executors" in the [doc root](https://docs.rs/smol/0.1.4/smol/) with more wording about executors and cases when to use them?

**Comment by Sherlock-Holo** [comment]
I think document it in doc root directly is better

when I read the doc, I think if I want to run multi-thread executor, I need to run "smile::run" on another threads, then continue use smol::run to run the "root future", but the better way is use block_on

**Comment by stjepang** [comment]
I have created a PR to address this: https://github.com/stjepang/smol/pull/70

Does this look better now? Let me know!

**Comment by pkorotkov** [comment]
@stjepang Looks a way better, but I believe it'd nice to include a variation on the code from the first @Sherlock-Holo 's comment. IMHO, it's also worth mentioning that calling `smol::block_on` with no executors running silently blocks the thread.

**Comment by zicklag** [comment]
> IMHO, it's also worth mentioning that calling smol::block_on with no executors running silently blocks the thread.

That is definitely a point that I would want to know. I didn't know that until I read that comment.

**Comment by stjepang** [comment]
> but I believe it'd be nice to include a variation on the code from the first @Sherlock-Holo 's comment.

There is a variation of that in examples for the `run()` function:

```rust
/// Multi-threaded executor:
///
/// ```no_run
/// use futures::future;
/// use smol::Task;
/// use std::thread;
///
/// // Same number of threads as there are CPU cores.
/// let num_threads = num_cpus::get().max(1);
///
/// // Create an executor thread pool.
/// for _ in 0..num_threads {
///     // A pending future is one that simply yields forever.
///     thread::spawn(|| smol::run(future::pending::<()>()));
/// }
///
/// // No need to `run()`, now we can just block on the main future.
/// smol::block_on(async {
///     Task::spawn(async {
///         println!("Hello from an executor thread!");
///     })
///     .await;
/// });
/// ```
```

> That is definitely a point that I would want to know. I didn't know that until I read that comment.

In lib.rs we have this sentence:
```rust
//! There is also [`block_on()`], which blocks the thread until a future completes, but it doesn't
//! do anything else besides that.
```

So I believe both points are addressed adequatly, but clearly they aren't, so I'll admit I'm a bit confused here - how can I make those sentences more visible?

**Comment by zicklag** [comment]
To me the first point about how to setup a multi-threaded executor was clear enough to me from the `run()` docs.

With block on "but it doesn't do anything else besides that" sounded a little unclear to me. Maybe something like:

> There is also [`block_on()`], which blocks the thread until a future completes, but it doesn't do anything else besides that. This means that if there are no threads currently executing the `run()` function, `block_on()` will block the thread indefinitely.

**Comment by stjepang** [comment]
Makes sense, thank you! Okay I've expanded that comment in lib.rs - how about now? :)

**Comment by zicklag** [comment]
Almost. :) It is still just a little difficult for me, as someone who doesn't fully understand the inner workings of async, to make out the simple truth that I need to have `run()` running to have `block_on()` work at all.

Don't get me wrong, the info is technically in there, but maybe just one tiny extra comment.

```
//! There is also [`block_on()`], which blocks the current thread until a future completes, but it
//! doesn't poll the reactor or run executors. Async I/O and timers will not work and
//! [`block_on()`] will block indefinitely unless at least one thread is currently calling [`run()`].
```

**Comment by stjepang** [comment]
I see. We could even make it a slightly stronger suggestion to call `run()` in an another thread:

```rust
//! There is also [`block_on()`], which blocks the current thread until a future completes, but it
//! doesn't poll the reactor or run executors. When using [`block_on()`], make sure at least one
//! thread is calling [`run()`], or else I/O and timers will not work!
```

How about that?

**Comment by pkorotkov** [comment]
@stjepang Sounds good.

**Comment by stjepang** [comment]
Cool, thank you! :) I'm going to merge that PR now.

Please don't hesitate to reopen this issue if you feel like the docs still need some improvement!

**Comment by zicklag** [comment]
Looks good to me! :+1:
