### ISSUE TITLE
Use of crates that are written with smol with other runtimes

### ISSUE THREAD

**Issue by oblique** [stjepang/smol#64]
I planning to migrate a small library project that I have to smol. Before I start the migration I wanted to see how crates written with smol can be used in projects written with tokio. So I wrote the following example:

```rust
use futures::prelude::*;
use smol::{Async, Task};
use std::net::TcpStream;

async fn foo() {
    Task::spawn(async {
        let mut buf = [0u8; 1024];
        let mut s = Async::<TcpStream>::connect("127.0.0.1:4444").await.unwrap();

        s.write_all(b"write something\n").await.unwrap();
        let len = s.read(&mut buf).await.unwrap();

        println!("{}", std::str::from_utf8(&buf[..len]).unwrap());
    })
    .await
}

#[tokio::main]
async fn main() {
    // start smol runtime in a thread
    std::thread::spawn(|| smol::run(future::pending::<()>()));

    foo().await;
}
```

I notice that without `std::thread::spawn(|| smol::run(future::pending::<()>()))` my example doesn't work.

My question now is: Should I require from users of my crate to have at least one instance of `smol::run`? What if smol spawns a new thread automatically if is no `smol::run` instance exists?

**Comment by stjepang** [comment]
Here's how you can make smol and tokio work together...

Solution 1: set up tokio context inside smol:

```rust
use std::thread;

use futures::prelude::*;
use tokio::runtime;

#[tokio::main]
async fn main() {
    let handle = runtime::Handle::current();
    thread::spawn(move || handle.enter(|| smol::run(future::pending::<()>())));

    // ...
}
```

Solution 2: enable the `"tokio02"` feature in smol, which creates a tokio context inside smol for you:

```rust
fn main() {
    smol::run(async {
        tokio::task::spawn(async {
            // ...
        });

        // ...
    })
}
```

I think the decision on what to do should be left to the user. After all, the user is the one that is implementing the `main` function.

**Comment by oblique** [comment]
Thanks! I forgot about `handle::enter`.
