### ISSUE TITLE
Rename the examples directory

### ISSUE THREAD

**Issue by stjepang** [stjepang/smol#72]
I'm considering renaming the `examples` directory to something else, perhaps `demos`. I find two things about the current setup inconvenient:

1. It's hard to add new examples because we need to add an `[[example]]` section per example to `examples/Cargo.toml`. I find this inconvenient because sometimes it's nice to add a quick temporary example for testing.

2. You need to be in the `examples` directory to run examples.

A possible solution to this would be to:

* rename `examples` to `demo`
* delete `autoexamples = false`
* add `demo` to `default-members` list in the `[workspace]` section
* perhaps change examples to bins

In that case, we could do `cargo run --bin ctrl-c` from the root of the repository.

**Comment by tshepang** [comment]
I can do this if you want... looks like easy way to contribute

**Comment by stjepang** [comment]
@tshepang Go ahead! :)
