### ISSUE TITLE
What happens to running tasks when `run()` exits?

### ISSUE THREAD

**Issue by zicklag** [stjepang/smol#76]
So I've got a `smol` thread pool that I've started using a `piper::Event` derive construct to block the `run()` function and make sure the thread pool stays open until the shutdown flag is set to `true`.

I also have some background tasks that do stuff like listen waiting on channels for stuff they need, etc.

My question is what happens to the tasks such as the background tasks that are sitting around waiting for channels when the `run()` function exits because a shutdown has been triggered the `Event` unblocks?

Do all of the futures that are in progress get canceled?

**Comment by laizy** [comment]
If I understand the code correctly:
- for tasks created with `Task::spawn`: they will be pushed to the global injector queue, so when other `run` method called, tasks will be polled again.
- for tasks created with `Task::local`: they will be dropped.
- for tasks created with `Task::blocking`: they will continue to work.

**Comment by zicklag** [comment]
OK, so then if I want to make sure certain things are finished, I need to make sure those tasks are done before shutting down the executor threads.

I think that makes sense because that way the user controls how to keep alive or not keep alive the tasks when shutting down.

**Comment by stjepang** [comment]
That's correct. I'm considering creating some kind of task queue that would give you a bit more control over the lifetime of tasks:

```rust
struct TaskQueue;

impl TaskQueue {
    fn spawn<T>(f: impl Future<Output = T> + Send + 'static) -> Task<T>;

    fn run<T>(f: impl Future<Output = T>) -> T;

    async fn shutdown(&self);
}
```

**Comment by zicklag** [comment]
Oh, that would be kind of cool. :)

The thing I am needing to account for in my app is:

  - I need a way to signal to interested tasks that a shutdown should be initiated
  - I need a way to make sure that certain tasks, after the shutdown has been initiated, are run until they are done with what they are doing

It amounts to sort of a combination of the [`ChangeNotifier`](https://github.com/stjepang/piper/pull/11#issuecomment-623089210) I was experimenting with for handling the shutdown signal, and a [`WaitGroup`](https://docs.rs/crossbeam/0.7.3/crossbeam/sync/struct.WaitGroup.html) to make sure that the all of the tasks that need to finish are done.

Still this could change as I'm still in the middle of refactoring this system I'm working with from non-async to async so I'm not sure that is the final design I'm going to end up with yet.

I might experiment with a `TaskQueue` abstraction along the lines of what you have above and create a PR with what I end up with.

**Comment by stjepang** [comment]
There is no `smol: run()` anymore.

**Comment by zicklag** [comment]
Well that makes it easy to think about. Good job! :smiley:
