### ISSUE TITLE
Question about IoEvent ?

### ISSUE THREAD

**Issue by yjhmelody** [stjepang/smol#78]
Does `writer` and `reader` play any real role in reading and writing communication here?
I find that writer write one byte in `notify` and reader read bytes in `clears`. But it seems that
the `flag` value does not depend on these bytes, it's just depend on some atomic ops.

**Comment by stjepang** [comment]
They do have a role :) The `flag` is there just to avoid sending into the socket if the socket is already full (we assume it's capacity is 1 byte). It's merely an optimization.

**Comment by yjhmelody** [comment]
I got it. Thanks
